/* TODO:
- Change DEFAULT constants to generated by functions
 */

const range = (start, end, length = end - start + 1) =>
  Array.from({ length }, (_, i) => start + i);

let COMBINATION_STR_DEFAULT = "1234";
let TIME_REST_DEFAULT = 10;
// let ITERATIONS_DEFAULT = 5;
let ITERATIONS_DEFAULT = generate_iterations();

function fill_placeholders(
  combination_str = COMBINATION_STR_DEFAULT,
  time_rest = TIME_REST_DEFAULT,
  iterations = ITERATIONS_DEFAULT
) {
  //  fill input forms with default or generated values
  document.getElementsByName("combination")[0].placeholder = combination_str;
  document.getElementsByName("time_rest")[0].placeholder = time_rest;
  document.getElementsByName("iterations")[0].placeholder = iterations;
}

function get_data() {
  let combination_str = document.getElementsByName("combination")[0].value;
  let time_rest = document.getElementsByName("time_rest")[0].value;
  let iterations = document.getElementsByName("iterations")[0].value;

  // If user doesn't fill some input, use deafault constants
  if (combination_str === "") {
    combination_str = COMBINATION_STR_DEFAULT;
  }
  if (time_rest === "") {
    time_rest = TIME_REST_DEFAULT;
  }
  if (iterations === "") {
    iterations = ITERATIONS_DEFAULT;
  }
  alert(combination_str + time_rest + iterations);
}

// functions for data random generation
function randomChoice(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function generate_iterations(level) {
  return randomChoice(range(1, 3));
}

// function generate_data
//   {
//   let combination_str = COMBINATION_STR_DEFAULT;
//    = TIME_REST_DEFAULT;
//   let iterations = ITERATIONS_DEFAULT;
//   return (combination_str, time_rest, iterations)
//   };

fill_placeholders();
document.getElementById("btn_play").onclick = get_data;
